GEODE-4882: Add FlakyTest category to AnalyzeConnectorsSerializablesJUnitTest
Test testSanctionedClassesExistAndDoDeserialize is failing intermittently:

org.apache.geode.cache.CacheClosedException: Could not PDX serialize because the cache was closed