fixing TODO in MsgStreamerList after seeing a thread create a VersionedMsgStreamer
the test doesn't have multiple versions, so I think this TODO is relevant
to the SSL decryption exceptions we're seeing (GEODE-8020).

[warn 2020/04/28 14:22:11.075 PDT <vm_0_thr_4_bridge1_host1_12580> tid=0x86] BRUCE:
java.lang.Exception: stack trace
  at org.apache.geode.internal.net.BufferPool.acquireDirectBuffer(BufferPool.java:115)
  at org.apache.geode.internal.net.BufferPool.acquireDirectSenderBuffer(BufferPool.java:64)
  at org.apache.geode.internal.tcp.MsgStreamer.<init>(MsgStreamer.java:132)
  at org.apache.geode.internal.tcp.VersionedMsgStreamer.<init>(VersionedMsgStreamer.java:37)
  at org.apache.geode.internal.tcp.MsgStreamer.create(MsgStreamer.java:199)