GEODE-7541: revert one change (#4526)
One of the changes for this ticket is causing unit test failures on
some machines - especially Macs - in the form of

java.lang.RuntimeException: Failed to start locator
      Caused by:
      org.apache.geode.GemFireConfigException: This process is attempting to join with a loopback address (gzhou-mbpro/127.0.0.1) using a locator that does not have a local address (/10.255.200.197:60167). On Unix this usually means that /etc/hosts is misconfigured.